print("Welcome to your adventure simulator. I am going to ask you a bunch of questions and then create an epic story with you as the star!")
print()
name =  input("What is your name?: ")
enemy = input("What is your worst enemy’s name?: ")
power = input("What is your superpower?: ")
location = input("Where do you live?: ")
food =input("What is your favorite food?: ")
print()
print("Hello","\033[31m", name, "\033[0m", "Your ability to", "\033[33m", power, "\033[0m", "will make sure you never have to look at", "\033[36m", enemy, "\033[0m", "again. Go eat", food, "as you walk down the streets of", location, "and use", power, "for good and not evil!")